name: IaC pipeline

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - IaC-pipeline.yml

pool:
  vmImage: ubuntu-latest

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'UdacityDS-70'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.8
  pythonVersion: '3.8'

stages:
- stage: iac
  displayName: Apply IaC
  pool:
    vmImage: $(vmImageName)
  jobs:
  - job: BuildJob
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: '1.7.1'