name: Azure Pipelines

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - test-pool.yaml

# ToDo: Replace the agent pool name, if you are using Udacity Cloud lab. 
# Otherwise, comment out the line below. 
# pool: myAgentPool

variables:
  python.version: '3.7.6'
  # ToDo: Replace the service connection name as used in the DevOps project settings
  azureServiceConnectionId: 'UdacityDS-51'
  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  # Environment name
  environmentName: 'test'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  # Agemt pool name
  agentPoolName: 'Default'

stages:
- stage: Pool_Tests
  jobs:
  - deployment: Pool_Tests
    environment:
      name:  'test'
      resourceType: VirtualMachine
    # pool: $(agentPoolName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            displayName: Pool
            inputs:
              targetType: 'inline'
              script: |
                echo "hello world"
          - task: NodeTool@0
            displayName: Install Node.js v16.20.2
            inputs:
              versionSpec: '16.20.2'
          
          - task: Bash@2
            displayName: Install Newman
            inputs:
              script: |
                npm install -g newman